/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 1. 《道德浪女》的独立侧边栏
  ethicalSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ethical_slut', // 只抓取 ethical_slut 文件夹里的内容
    },
  ],

  // 2. 《超越单偶制》的独立侧边栏
  beyondSidebar: [
    {
      type: 'autogenerated',
      dirName: 'beyond_monogamy',
    },
  ],

  // 3. 《不止于二》的独立侧边栏
  moreSidebar: [
    {
      type: 'autogenerated',
      dirName: 'more_than_two',
    },
  ],

  // 4. 《走向开放》的独立侧边栏
  openingSidebar: [
    {
      type: 'autogenerated',
      dirName: 'opening_up',
    },
  ],
};

module.exports = sidebars;